# Generated by Django 2.1.2 on 2019-03-09 14:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('therapist', '0002_appointment_valid_till'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllAppointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointmenttime', models.DateTimeField()),
                ('datecreated', models.DateTimeField(default=datetime.datetime.now)),
                ('approved', models.CharField(default=1, max_length=1)),
                ('payed', models.BooleanField(default=False)),
                ('valid_till', models.DateTimeField(default=datetime.datetime.now)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='therapist.Therapist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
