# Generated by Django 2.1.2 on 2019-04-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botchat',
            name='message_audio',
            field=models.FileField(default=None, upload_to='bot_audio'),
        ),
    ]
