# Generated by Django 2.1.2 on 2019-04-12 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0007_transaction_appointment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='appointment_id',
            new_name='appointment',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='therapist_id',
            new_name='therapist',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='user_id',
            new_name='user',
        ),
    ]
